
export class HTTPConstants {

  static EPT_APP_HEADER_RESPONSE_CODE = 'EPT_APP_RESPONSE_CODE';
  static  EPT_APP_HEADER_REASON_CODE = 'EPT_APP_REASON_CODE';
  static EPT_STATUS_CODE_SUCCESS = '200';
  static EPT_STATUS_CODE_FAILURE = '400';
  static EPT_APP_REASON_CODE_EMPLOYEE_ADDED = '201';
  static EPT_APP_REASON_CODE_EMPLOYEE_EXISTS = '401';
  static EPT_APP_REASON_CODE_INTERNAL_ERROR = '501';

}
